package com.example.zenfit

object ApiConfig {
    private const val BASE_URL = "http://192.168.18.170/zenfit/"
    const val LOGIN_URL = "${BASE_URL}login.php"
    const val SIGNUP_URL = "${BASE_URL}signup.php"
    const val FORGOT_PASSWORD_URL = "${BASE_URL}forgot_password.php"
    const val RESET_PASSWORD_URL = "${BASE_URL}reset_password.php"
    const val CHANGE_PASSWORD_URL = "${BASE_URL}change_password.php"
    const val GET_ACCOUNT_URL = "${BASE_URL}account.php"
    const val UPDATE_ACCOUNT_URL = "${BASE_URL}update_account.php"
    const val DELETE_ACCOUNT_URL = "${BASE_URL}delete_account.php"
    const val UPDATE_PROFILE_URL = "${BASE_URL}update_account.php"
    const val GET_PROFILE_URL = "${BASE_URL}get_profile.php"
    const val GET_USER_POSTS_URL = "${BASE_URL}get_user_posts.php"
    const val UPDATE_MOOD_URL = "${BASE_URL}update_mood.php"
    const val GET_MOOD_URL = "${BASE_URL}get_mood.php"
    const val UPLOAD_MEAL_URL = "${BASE_URL}upload_meal.php"
    const val GET_MEALS_URL = "${BASE_URL}get_meals.php"
    const val GET_MEALS_BY_DATE_URL = "${BASE_URL}get_meals_by_date.php"
    const val GET_MEAL_IDEAS_URL = "${BASE_URL}get_meal_ideas.php"
    const val UPLOAD_POST_URL = "${BASE_URL}upload_post.php"

    const val GET_EXERCISES_URL = "${BASE_URL}get_exercises.php"
    const val UPDATE_EXERCISE_URL = "${BASE_URL}update_exercise.php"
    const val CREATE_WORKOUT_URL = "${BASE_URL}create_workout.php"
    const val GET_WORKOUTS_URL = "${BASE_URL}get_workouts.php"
    const val SAVE_WORKOUT_HISTORY_URL = "$BASE_URL/save_workout_history.php"
    const val GET_WORKOUT_HISTORY_URL = "${BASE_URL}get_workout_history.php"
    const val DELETE_WORKOUT_HISTORY_URL = "${BASE_URL}delete_workout_history.php"
    const val SETUP_ACCOUNT_URL = "${BASE_URL}setup_account.php"
    const val DELETE_WORKOUT_URL = "${BASE_URL}delete_workout.php"
    const val UPDATE_FCM_TOKEN_URL = "http://10.0.2.2/zenfitbackend/update_fcm_token.php"
    const val SEND_WORKOUT_NOTIFICATION_URL = "http://10.0.2.2/zenfitbackend/send_workout_notification.php"
}
